apiVersion: apps/v1
kind: Deployment
metadata:
  name: wappone
  labels:
    app: demo
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: demo
    spec:
      containers:
      - name: wappone
        image: registry.cn-shanghai.aliyuncs.com/larus/webappone:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9999
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 9999
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
